# -*- coding: utf-8 -*-
{
    'name': 'School Demo',
    'version': '8.0.1.1.0',
    'category': 'School',
    'depends': [
        'school',
        'school_attendance',
        'school_event',
        'school_fees',
        'school_hostel',
        'school_transport',
        'student_evaluation',
        'assignment',
        'barcode_report',
        'timetable',
        'exam',
        'library',
        'openmadrassa_base',
    ],
    'data': [],
    'author': 'Eman Taha',
    'installable': True,
    'application': True,
    'auto_install': False,
}